### ISSUE TITLE
Reference needed

### ISSUE THREAD

**Issue by arjunvkurup** [kunqil/Quadcopter-Simulation#1]
Can you provide the references and if there are any resource to follow, that too. I'm doing my project on modeling quadcopter using MATLAB, so it would be helpful.

**Comment by kunqil** [comment]
This demo may help，https://www.mathworks.com/videos/animating-an-objects-trajectory-in-matlab-with-hgtransform-97224.html

**Comment by kunqil** [comment]
And the modeling procedure was uploaded as Quadcopter Simulation Reference Manual
